sudo: true
language: python

matrix:
    fast_finish: true

branches:
  only:
    - /master/

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash $HOME/islandora/.scripts/deploy_documentation.sh; fi'

deploy:
  provider: pages
  local_dir: $HOME/islandora/site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
